module.exports = {
  "accent": "hsl(var(--accent))",
  "accent-foreground": "hsl(var(--accent-foreground))",
  "background": "hsl(var(--background))",
  "border": "hsl(var(--border))",
  "card": "hsl(var(--card))",
  "destructive": "hsl(var(--destructive))",
  "destructive-foreground": "hsl(var(--destructive-foreground))",
  "foreground": "hsl(var(--foreground))",
  "input": "hsl(var(--input))",
  "muted": "hsl(var(--muted))",
  "muted-foreground": "hsl(var(--muted-foreground))",
  "popover": "hsl(var(--popover))",
  "primary": "hsl(var(--primary))",
  "primary-foreground": "hsl(var(--primary-foreground))",
  "ring": "hsl(var(--ring))",
  "secondary": "hsl(var(--secondary))",
  "secondary-foreground": "hsl(var(--secondary-foreground))",
  "transparent": "transparent",
  "current": "currentColor",
  "inherit": "inherit"
};
