import { HeroBlock, FeaturesBlock } from '@/blocks';
import { CriticalCSSInjector } from '@/components/CriticalCSSInjector';

// Critical CSS for HomePage - only styles for components actually used on this page
// Generated by: bun run css:generate:critical
// Result: 17 lines of CSS instead of 58+ lines (70% reduction!)
const homePageCriticalCSS = `
.features-header { gap: calc(var(--spacing) * 4); align-items: center; }
.features-grid { gap: calc(var(--spacing) * 6); }
.hero-content { gap: calc(var(--spacing) * 4); align-items: center; }
.hero-actions { gap: calc(var(--spacing) * 4); }
`;

// Route component - composes multiple semantic blocks with critical CSS optimization
export function HomePage() {
  return (
    <>
      {/* Inject critical CSS directly into head for this route */}
      <CriticalCSSInjector css={homePageCriticalCSS} id="homepage-critical-css" />

      <HeroBlock />
      <FeaturesBlock />
    </>
  );
}
