/**
 * Generated by @ui8kit/generator - variant elements
 * Do not edit manually - this file is auto-generated
 */

import type { ReactNode, ComponentProps } from "react";
import { Badge } from "@ui8kit/core";

/**
 * Badge variant elements for documentation and reuse.
 * Each element has a single variant with corresponding data-class attribute.
 */
export function BadgeElements() {
  return (
    <>
  {/* Base */}
  <Badge data-class="badge">Badge</Badge>
  {/* Variants */}
  <Badge data-class="badge-size-lg" size="lg">BadgeSize Lg</Badge>
  <Badge data-class="badge-size-sm" size="sm">BadgeSize Sm</Badge>
  <Badge data-class="badge-size-xs" size="xs">BadgeSize Xs</Badge>
  <Badge data-class="badge-variant-destructive" variant="destructive">BadgeVariant Destructive</Badge>
  <Badge data-class="badge-variant-info" variant="info">BadgeVariant Info</Badge>
  <Badge data-class="badge-variant-outline" variant="outline">BadgeVariant Outline</Badge>
  <Badge data-class="badge-variant-secondary" variant="secondary">BadgeVariant Secondary</Badge>
  <Badge data-class="badge-variant-success" variant="success">BadgeVariant Success</Badge>
  <Badge data-class="badge-variant-warning" variant="warning">BadgeVariant Warning</Badge>
    </>
  );
}

/**
 * Reusable badge element components.
 * Accept children and props for composition.
 */
/** Base Badge with semantic data-class */
export const BadgeElement = ({ children, ...props }: Omit<ComponentProps<typeof Badge>, "data-class"> & { children?: ReactNode }) => (
  <Badge data-class="badge" {...props}>{children ?? "Badge"}</Badge>
);

/** Badge with lg variant */
export const BadgeLg = ({ children, ...props }: Omit<ComponentProps<typeof Badge>, "data-class" | "size"> & { children?: ReactNode }) => (
  <Badge data-class="badge-size-lg" size="lg" {...props}>{children ?? "BadgeSize Lg"}</Badge>
);

/** Badge with sm variant */
export const BadgeSm = ({ children, ...props }: Omit<ComponentProps<typeof Badge>, "data-class" | "size"> & { children?: ReactNode }) => (
  <Badge data-class="badge-size-sm" size="sm" {...props}>{children ?? "BadgeSize Sm"}</Badge>
);

/** Badge with xs variant */
export const BadgeXs = ({ children, ...props }: Omit<ComponentProps<typeof Badge>, "data-class" | "size"> & { children?: ReactNode }) => (
  <Badge data-class="badge-size-xs" size="xs" {...props}>{children ?? "BadgeSize Xs"}</Badge>
);

/** Badge with destructive variant */
export const BadgeDestructive = ({ children, ...props }: Omit<ComponentProps<typeof Badge>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Badge data-class="badge-variant-destructive" variant="destructive" {...props}>{children ?? "BadgeVariant Destructive"}</Badge>
);

/** Badge with info variant */
export const BadgeInfo = ({ children, ...props }: Omit<ComponentProps<typeof Badge>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Badge data-class="badge-variant-info" variant="info" {...props}>{children ?? "BadgeVariant Info"}</Badge>
);

/** Badge with outline variant */
export const BadgeOutline = ({ children, ...props }: Omit<ComponentProps<typeof Badge>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Badge data-class="badge-variant-outline" variant="outline" {...props}>{children ?? "BadgeVariant Outline"}</Badge>
);

/** Badge with secondary variant */
export const BadgeSecondary = ({ children, ...props }: Omit<ComponentProps<typeof Badge>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Badge data-class="badge-variant-secondary" variant="secondary" {...props}>{children ?? "BadgeVariant Secondary"}</Badge>
);

/** Badge with success variant */
export const BadgeSuccess = ({ children, ...props }: Omit<ComponentProps<typeof Badge>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Badge data-class="badge-variant-success" variant="success" {...props}>{children ?? "BadgeVariant Success"}</Badge>
);

/** Badge with warning variant */
export const BadgeWarning = ({ children, ...props }: Omit<ComponentProps<typeof Badge>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Badge data-class="badge-variant-warning" variant="warning" {...props}>{children ?? "BadgeVariant Warning"}</Badge>
);
