/**
 * Generated by @ui8kit/generator - variant elements
 * Do not edit manually - this file is auto-generated
 */

import type { ReactNode, ComponentProps } from "react";
import { Button, Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, Grid, Image } from "@ui8kit/core";

/**
 * Button variant elements for documentation and reuse.
 * Each element has a single variant with corresponding data-class attribute.
 */
export function ButtonElements() {
  return (
    <>
  {/* Base */}
  <Button data-class="button">Button</Button>
  {/* Variants */}
  <Button data-class="button-size-icon" size="icon">ButtonSize Icon</Button>
  <Button data-class="button-size-lg" size="lg">ButtonSize Lg</Button>
  <Button data-class="button-size-md" size="md">ButtonSize Md</Button>
  <Button data-class="button-size-sm" size="sm">ButtonSize Sm</Button>
  <Button data-class="button-size-xl" size="xl">ButtonSize Xl</Button>
  <Button data-class="button-size-xs" size="xs">ButtonSize Xs</Button>
  <Button data-class="button-variant-destructive" variant="destructive">ButtonVariant Destructive</Button>
  <Button data-class="button-variant-ghost" variant="ghost">ButtonVariant Ghost</Button>
  <Button data-class="button-variant-link" variant="link">ButtonVariant Link</Button>
  <Button data-class="button-variant-outline" variant="outline">ButtonVariant Outline</Button>
  <Button data-class="button-variant-primary" variant="primary">ButtonVariant Primary</Button>
  <Button data-class="button-variant-secondary" variant="secondary">ButtonVariant Secondary</Button>
    </>
  );
}

/**
 * Reusable button element components.
 * Accept children and props for composition.
 */
/** Base Button with semantic data-class */
export const ButtonElement = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class"> & { children?: ReactNode }) => (
  <Button data-class="button" {...props}>{children ?? "Button"}</Button>
);

/** Button with icon variant */
export const ButtonIcon = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class" | "size"> & { children?: ReactNode }) => (
  <Button data-class="button-size-icon" size="icon" {...props}>{children ?? "ButtonSize Icon"}</Button>
);

/** Button with lg variant */
export const ButtonLg = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class" | "size"> & { children?: ReactNode }) => (
  <Button data-class="button-size-lg" size="lg" {...props}>{children ?? "ButtonSize Lg"}</Button>
);

/** Button with md variant */
export const ButtonMd = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class" | "size"> & { children?: ReactNode }) => (
  <Button data-class="button-size-md" size="md" {...props}>{children ?? "ButtonSize Md"}</Button>
);

/** Button with sm variant */
export const ButtonSm = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class" | "size"> & { children?: ReactNode }) => (
  <Button data-class="button-size-sm" size="sm" {...props}>{children ?? "ButtonSize Sm"}</Button>
);

/** Button with xl variant */
export const ButtonXl = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class" | "size"> & { children?: ReactNode }) => (
  <Button data-class="button-size-xl" size="xl" {...props}>{children ?? "ButtonSize Xl"}</Button>
);

/** Button with xs variant */
export const ButtonXs = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class" | "size"> & { children?: ReactNode }) => (
  <Button data-class="button-size-xs" size="xs" {...props}>{children ?? "ButtonSize Xs"}</Button>
);

/** Button with destructive variant */
export const ButtonDestructive = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Button data-class="button-variant-destructive" variant="destructive" {...props}>{children ?? "ButtonVariant Destructive"}</Button>
);

/** Button with ghost variant */
export const ButtonGhost = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Button data-class="button-variant-ghost" variant="ghost" {...props}>{children ?? "ButtonVariant Ghost"}</Button>
);

/** Button with link variant */
export const ButtonLink = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Button data-class="button-variant-link" variant="link" {...props}>{children ?? "ButtonVariant Link"}</Button>
);

/** Button with outline variant */
export const ButtonOutline = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Button data-class="button-variant-outline" variant="outline" {...props}>{children ?? "ButtonVariant Outline"}</Button>
);

/** Button with primary variant */
export const ButtonPrimary = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Button data-class="button-variant-primary" variant="primary" {...props}>{children ?? "ButtonVariant Primary"}</Button>
);

/** Button with secondary variant */
export const ButtonSecondary = ({ children, ...props }: Omit<ComponentProps<typeof Button>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Button data-class="button-variant-secondary" variant="secondary" {...props}>{children ?? "ButtonVariant Secondary"}</Button>
);
