/**
 * Generated by @ui8kit/generator - variant elements
 * Do not edit manually - this file is auto-generated
 */

import type { ReactNode, ComponentProps } from "react";
import { Button, Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, Grid, Image } from "@ui8kit/core";

/**
 * Image variant elements for documentation and reuse.
 * Each element has a single variant with corresponding data-class attribute.
 */
export function ImageElements() {
  return (
    <>
  {/* Base */}
  <Image data-class="image">Image</Image>
  {/* Variants */}
  <Image data-class="image-position-left-bottom" position="left-bottom">ImagePosition LeftBottom</Image>
  <Image data-class="image-position-left-top" position="left-top">ImagePosition LeftTop</Image>
  <Image data-class="image-position-right-bottom" position="right-bottom">ImagePosition RightBottom</Image>
  <Image data-class="image-position-right-top" position="right-top">ImagePosition RightTop</Image>
    </>
  );
}

/**
 * Reusable image element components.
 * Accept children and props for composition.
 */
/** Base Image with semantic data-class */
export const ImageElement = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class"> & { children?: ReactNode }) => (
  <Image data-class="image" {...props}>{children ?? "Image"}</Image>
);

/** Image with left-bottom variant */
export const ImageLeftBottom = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "position"> & { children?: ReactNode }) => (
  <Image data-class="image-position-left-bottom" position="left-bottom" {...props}>{children ?? "ImagePosition LeftBottom"}</Image>
);

/** Image with left-top variant */
export const ImageLeftTop = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "position"> & { children?: ReactNode }) => (
  <Image data-class="image-position-left-top" position="left-top" {...props}>{children ?? "ImagePosition LeftTop"}</Image>
);

/** Image with right-bottom variant */
export const ImageRightBottom = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "position"> & { children?: ReactNode }) => (
  <Image data-class="image-position-right-bottom" position="right-bottom" {...props}>{children ?? "ImagePosition RightBottom"}</Image>
);

/** Image with right-top variant */
export const ImageRightTop = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "position"> & { children?: ReactNode }) => (
  <Image data-class="image-position-right-top" position="right-top" {...props}>{children ?? "ImagePosition RightTop"}</Image>
);
