/**
 * Generated by @ui8kit/generator - variant elements
 * Do not edit manually - this file is auto-generated
 */

import type { ReactNode, ComponentProps } from "react";
import { Image } from "../components";
import type { ImageProps } from "../components";

/**
 * Image variant elements for documentation and reuse.
 * Each element has a single variant with corresponding data-class attribute.
 */
export function ImageElements() {
  return (
    <>
  {/* Base */}
  <Image data-class="image">Image</Image>
  {/* Variants */}
  <Image data-class="image-aspect-square" aspect="square">ImageAspect Square</Image>
  <Image data-class="image-aspect-video" aspect="video">ImageAspect Video</Image>
  <Image data-class="image-fit-contain" fit="contain">ImageFit Contain</Image>
  <Image data-class="image-fit-fill" fit="fill">ImageFit Fill</Image>
  <Image data-class="image-fit-none" fit="none">ImageFit None</Image>
  <Image data-class="image-fit-scale-down" fit="scale-down">ImageFit ScaleDown</Image>
  <Image data-class="image-position-bottom" position="bottom">ImagePosition Bottom</Image>
  <Image data-class="image-position-left" position="left">ImagePosition Left</Image>
  <Image data-class="image-position-left-bottom" position="left-bottom">ImagePosition LeftBottom</Image>
  <Image data-class="image-position-left-top" position="left-top">ImagePosition LeftTop</Image>
  <Image data-class="image-position-right" position="right">ImagePosition Right</Image>
  <Image data-class="image-position-right-bottom" position="right-bottom">ImagePosition RightBottom</Image>
  <Image data-class="image-position-right-top" position="right-top">ImagePosition RightTop</Image>
  <Image data-class="image-position-top" position="top">ImagePosition Top</Image>
  <Image data-class="image-withPlaceholder-with-placeholder" withPlaceholder="with-placeholder">ImageWithPlaceholder WithPlaceholder</Image>
    </>
  );
}

/**
 * Reusable image element components.
 * Accept children and props for composition.
 */
/** Base Image with semantic data-class */
export const ImageElement = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class"> & { children?: ReactNode }) => (
  <Image data-class="image" {...props}>{children ?? "Image"}</Image>
);

/** Image with square variant */
export const ImageSquare = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "aspect"> & { children?: ReactNode }) => (
  <Image data-class="image-aspect-square" aspect="square" {...props}>{children ?? "ImageAspect Square"}</Image>
);

/** Image with video variant */
export const ImageVideo = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "aspect"> & { children?: ReactNode }) => (
  <Image data-class="image-aspect-video" aspect="video" {...props}>{children ?? "ImageAspect Video"}</Image>
);

/** Image with contain variant */
export const ImageContain = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "fit"> & { children?: ReactNode }) => (
  <Image data-class="image-fit-contain" fit="contain" {...props}>{children ?? "ImageFit Contain"}</Image>
);

/** Image with fill variant */
export const ImageFill = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "fit"> & { children?: ReactNode }) => (
  <Image data-class="image-fit-fill" fit="fill" {...props}>{children ?? "ImageFit Fill"}</Image>
);

/** Image with none variant */
export const ImageNone = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "fit"> & { children?: ReactNode }) => (
  <Image data-class="image-fit-none" fit="none" {...props}>{children ?? "ImageFit None"}</Image>
);

/** Image with scale-down variant */
export const ImageScaleDown = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "fit"> & { children?: ReactNode }) => (
  <Image data-class="image-fit-scale-down" fit="scale-down" {...props}>{children ?? "ImageFit ScaleDown"}</Image>
);

/** Image with bottom variant */
export const ImageBottom = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "position"> & { children?: ReactNode }) => (
  <Image data-class="image-position-bottom" position="bottom" {...props}>{children ?? "ImagePosition Bottom"}</Image>
);

/** Image with left variant */
export const ImageLeft = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "position"> & { children?: ReactNode }) => (
  <Image data-class="image-position-left" position="left" {...props}>{children ?? "ImagePosition Left"}</Image>
);

/** Image with left-bottom variant */
export const ImageLeftBottom = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "position"> & { children?: ReactNode }) => (
  <Image data-class="image-position-left-bottom" position="left-bottom" {...props}>{children ?? "ImagePosition LeftBottom"}</Image>
);

/** Image with left-top variant */
export const ImageLeftTop = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "position"> & { children?: ReactNode }) => (
  <Image data-class="image-position-left-top" position="left-top" {...props}>{children ?? "ImagePosition LeftTop"}</Image>
);

/** Image with right variant */
export const ImageRight = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "position"> & { children?: ReactNode }) => (
  <Image data-class="image-position-right" position="right" {...props}>{children ?? "ImagePosition Right"}</Image>
);

/** Image with right-bottom variant */
export const ImageRightBottom = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "position"> & { children?: ReactNode }) => (
  <Image data-class="image-position-right-bottom" position="right-bottom" {...props}>{children ?? "ImagePosition RightBottom"}</Image>
);

/** Image with right-top variant */
export const ImageRightTop = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "position"> & { children?: ReactNode }) => (
  <Image data-class="image-position-right-top" position="right-top" {...props}>{children ?? "ImagePosition RightTop"}</Image>
);

/** Image with top variant */
export const ImageTop = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "position"> & { children?: ReactNode }) => (
  <Image data-class="image-position-top" position="top" {...props}>{children ?? "ImagePosition Top"}</Image>
);

/** Image with with-placeholder variant */
export const ImageWithPlaceholder = ({ children, ...props }: Omit<ComponentProps<typeof Image>, "data-class" | "withPlaceholder"> & { children?: ReactNode }) => (
  <Image data-class="image-withPlaceholder-with-placeholder" withPlaceholder="with-placeholder" {...props}>{children ?? "ImageWithPlaceholder WithPlaceholder"}</Image>
);
