/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for WordPress template contexts
 */
export interface WPFastyContext {
  /**
   * Site
   */
  site: {
    /**
     * Title
     */
    title: string;
    /**
     * Url
     */
    url: string;
    /**
     * Theme_url
     */
    theme_url: string;
    /**
     * Lang
     */
    lang: string;
    /**
     * Description
     */
    description: string;
    /**
     * Charset
     */
    charset: string;
    [k: string]: unknown;
  };
  /**
   * Menu
   */
  menu: {
    /**
     * Primary
     */
    primary: {
      /**
       * Items
       */
      items: {
        /**
         * Title
         */
        title: string;
        /**
         * Url
         */
        url: string;
        /**
         * Id
         */
        id: number;
        /**
         * Order
         */
        order: number;
        /**
         * Parent
         */
        parent:
        | null
        | string
        | {
          [k: string]: unknown;
        };
        /**
         * Classes
         */
        classes: string[];
        /**
         * Current
         */
        current: boolean;
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  page: {
    /**
     * Page
     */
    page: {
      /**
       * Title
       */
      title: string;
      /**
       * Content
       */
      content: string;
      /**
       * Slug
       */
      slug: string;
      /**
       * Url
       */
      url: string;
      /**
       * Id
       */
      id: number;
      /**
       * Excerpt
       */
      excerpt: string;
      /**
       * FeaturedImage
       */
      featuredImage: {
        /**
         * Url
         */
        url: string;
        /**
         * Width
         */
        width: number;
        /**
         * Height
         */
        height: number;
        /**
         * Alt
         */
        alt: string;
        [k: string]: unknown;
      };
      /**
       * Thumbnail
       */
      thumbnail: {
        /**
         * Url
         */
        url: string;
        /**
         * Width
         */
        width: number;
        /**
         * Height
         */
        height: number;
        /**
         * Alt
         */
        alt: string;
        [k: string]: unknown;
      };
      /**
       * Meta
       */
      meta: {
        /**
         * _edit_last
         */
        _edit_last: string;
        /**
         * _edit_lock
         */
        _edit_lock: string;
        [k: string]: unknown;
      };
      /**
       * Categories
       */
      categories: {
        /**
         * Name
         */
        name: string;
        /**
         * Url
         */
        url: string;
        /**
         * Id
         */
        /**
        id: number;
         * Slug
         */
        slug: string;
        /**
         * Description
         */
        description: string;
        /**
         * Count
         */
        count: number;
        [k: string]: unknown;
      }[];
      /**
       * Date
       */
      date: {
        /**
         * Formatted
         */
        formatted: string;
        /**
         * Display
         */
        display: string;
        /**
         * Modified
         */
        modified: string;
        /**
         * Modified_display
         */
        modified_display: string;
        /**
         * Timestamp
         */
        timestamp: number;
        /**
         * Year
         */
        year: string;
        /**
         * Month
         */
        month: string;
        /**
         * Day
         */
        day: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  archive: {
    /**
     * Archive
     */
    archive: {
      /**
       * Title
       */
      title: string;
      /**
       * Description
       */
      description: string;
      [k: string]: unknown;
    };
    /**
     * Posts
     */
    posts: {
      /**
       * Title
       */
      title: string;
      /**
       * Content
       */
      content: string;
      /**
       * Slug
       */
      slug: string;
      /**
       * Url
       */
      url: string;
      /**
       * Id
       */
      id: number;
      /**
       * Excerpt
       */
      excerpt: string;
      /**
       * FeaturedImage
       */
      featuredImage: {
        /**
         * Url
         */
        url: string;
        /**
         * Width
         */
        width: number;
        /**
         * Height
         */
        height: number;
        /**
         * Alt
         */
        alt: string;
        [k: string]: unknown;
      };
      /**
       * Thumbnail
       */
      thumbnail: {
        /**
         * Url
         */
        url: string;
        /**
         * Width
         */
        width: number;
        /**
         * Height
         */
        height: number;
        /**
         * Alt
         */
        alt: string;
        [k: string]: unknown;
      };
      /**
       * Meta
       */
      meta: {
        /**
         * _edit_last
         */
        _edit_last: string;
        /**
         * _edit_lock
         */
        _edit_lock: string;
        [k: string]: unknown;
      };
      /**
       * Categories
       */
      categories: {
        /**
         * Name
         */
        name: string;
        /**
         * Url
         */
        url: string;
        /**
         * Id
         */
        id: number;
        /**
         * Slug
         */
        slug: string;
        /**
         * Description
         */
        description: string;
        /**
         * Count
         */
        count: number;
        [k: string]: unknown;
      }[];
      /**
       * Date
       */
      date: {
        /**
         * Formatted
         */
        formatted: string;
        /**
         * Display
         */
        display: string;
        /**
         * Modified
         */
        modified: string;
        /**
         * Modified_display
         */
        modified_display: string;
        /**
         * Timestamp
         */
        timestamp: number;
        /**
         * Year
         */
        year: string;
        /**
         * Month
         */
        month: string;
        /**
         * Day
         */
        day: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    /**
     * Pagination
     */
    pagination: {
      /**
       * Prev_url
       */
      prev_url: string;
      /**
       * Next_url
       */
      next_url: string;
      /**
       * Pages
       */
      pages: {
        /**
         * Number
         */
        number: number;
        /**
         * Url
         */
        url: string;
        /**
         * Is_current
         */
        is_current: boolean;
        [k: string]: unknown;
      }[];
      /**
       * Current
       */
      current: number;
      /**
       * Total
       */
      total: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
