import { writeFile, mkdir } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import type { 
  GeneratedMdxPage, 
  GeneratedDemo,
} from '../core/types'

// ============================================================================
// Liquid Emitter - Writes generated content to Liquid templates
// ============================================================================

export interface EmitOptions {
  /**
   * Output directory for Liquid page templates
   */
  pagesDir: string
  
  /**
   * Output directory for demo partials
   */
  demosDir: string
  
  /**
   * Base path for URLs
   */
  basePath: string
}

/**
 * Emit generated MDX page to Liquid template
 */
export async function emitLiquidPage(
  page: GeneratedMdxPage,
  options: EmitOptions
): Promise<void> {
  const { pagesDir, demosDir } = options
  
  // Calculate output path
  const relativePath = urlPathToFilePath(page.urlPath, options.basePath)
  const outputPath = join(pagesDir, `${relativePath}.liquid`)
  
  // Ensure directory exists
  await mkdir(dirname(outputPath), { recursive: true })
  
  // Write main page template
  await writeFile(outputPath, page.liquidContent, 'utf-8')
  console.log(`  → ${outputPath}`)
  
  // Write demo partials
  if (page.demos.length > 0) {
    await mkdir(demosDir, { recursive: true })
    
    for (const demo of page.demos) {
      await emitDemoPartial(demo, demosDir)
    }
  }
}

/**
 * Emit demo partial
 */
async function emitDemoPartial(
  demo: GeneratedDemo,
  demosDir: string
): Promise<void> {
  const outputPath = join(demosDir, `${demo.id}.liquid`)
  
  const content = [
    `{% comment %}`,
    `  Demo partial: ${demo.id}`,
    `  Generated by @ui8kit/mdx-react`,
    `{% endcomment %}`,
    ``,
    demo.liquidContent,
  ].join('\n')
  
  await writeFile(outputPath, content, 'utf-8')
  console.log(`    → ${outputPath}`)
}

/**
 * Convert URL path to file path
 * /docs/components/button → components/button
 */
function urlPathToFilePath(urlPath: string, basePath: string): string {
  let path = urlPath
  
  // Remove base path prefix
  if (basePath && path.startsWith(basePath)) {
    path = path.slice(basePath.length)
  }
  
  // Remove leading slash
  path = path.replace(/^\//, '')
  
  // Handle empty path (index)
  if (!path) {
    path = 'index'
  }
  
  return path
}

/**
 * Generate docs layout Liquid template
 */
export function generateDocsLayoutTemplate(): string {
  return `{% comment %}
  Documentation page layout
  Includes sidebar, content, and TOC
{% endcomment %}

<!DOCTYPE html>
<html lang="{{ site.lang | default: 'en' }}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ page_title }} - {{ site.title }}</title>
  {% if page_description %}
  <meta name="description" content="{{ page_description }}">
  {% endif %}
  <link rel="stylesheet" href="/assets/css/styles.css">
</head>
<body>
  <div data-class="docs-layout">
    <!-- Sidebar -->
    <aside data-class="docs-sidebar">
      {% include 'partials/docs-nav.liquid' %}
    </aside>
    
    <!-- Main Content -->
    <main data-class="docs-main">
      <article data-class="docs-article">
        {% if page_title %}
        <header data-class="docs-header">
          <h1 data-class="docs-title">{{ page_title }}</h1>
          {% if page_description %}
          <p data-class="docs-description">{{ page_description }}</p>
          {% endif %}
        </header>
        {% endif %}
        
        <div data-class="docs-content">
          {{ content }}
        </div>
      </article>
      
      <!-- Table of Contents -->
      {% if page_toc.size > 0 %}
      <aside data-class="docs-toc">
        <nav data-class="toc" aria-label="Table of Contents">
          <h2 data-class="toc-title">On This Page</h2>
          <ul data-class="toc-list">
            {% for item in page_toc %}
            <li data-class="toc-item" data-depth="{{ item.depth }}">
              <a href="#{{ item.slug }}" data-class="toc-link">{{ item.text }}</a>
            </li>
            {% endfor %}
          </ul>
        </nav>
      </aside>
      {% endif %}
    </main>
  </div>
</body>
</html>
`
}

/**
 * Generate docs navigation partial template
 */
export function generateDocsNavTemplate(): string {
  return `{% comment %}
  Documentation navigation sidebar
  Uses docs-nav.json data
{% endcomment %}

<nav data-class="sidebar" aria-label="Documentation">
  {% for section in docs_nav.items %}
  <div data-class="sidebar-section">
    {% if section.path %}
    <a href="{{ section.path }}" data-class="sidebar-heading">{{ section.title }}</a>
    {% else %}
    <h3 data-class="sidebar-heading">{{ section.title }}</h3>
    {% endif %}
    
    {% if section.children.size > 0 %}
    <ul data-class="sidebar-list">
      {% for item in section.children %}
      <li data-class="sidebar-item">
        <a href="{{ item.path }}" data-class="sidebar-link{% if page.url == item.path %} active{% endif %}">
          {{ item.title }}
        </a>
        
        {% if item.children.size > 0 %}
        <ul data-class="sidebar-sublist">
          {% for subitem in item.children %}
          <li data-class="sidebar-item">
            <a href="{{ subitem.path }}" data-class="sidebar-link{% if page.url == subitem.path %} active{% endif %}">
              {{ subitem.title }}
            </a>
          </li>
          {% endfor %}
        </ul>
        {% endif %}
      </li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
  {% endfor %}
</nav>
`
}
