import { ComponentStyle } from './parser.js';

/**
 * Known utility props from utility-props.map.ts
 * This should match the keys from utilityPropsMap
 */
const UTILITY_PROPS = new Set([
  'absolute', 'accent', 'aspect', 'auto', 'basis', 'bg', 'block', 'border', 'bottom', 'box',
  'break', 'capitalize', 'clear', 'col', 'cols', 'container', 'content', 'cursor', 'decoration',
  'delay', 'direction', 'display', 'duration', 'ease', 'fill', 'fixed', 'flex', 'float', 'flow',
  'font', 'gap', 'gradient', 'grid', 'grow', 'h', 'hidden', 'hyphens', 'inset', 'invert', 'items',
  'justify', 'leading', 'left', 'line', 'list', 'lowercase', 'm', 'max', 'mb', 'me', 'min', 'mix',
  'ml', 'mr', 'ms', 'mt', 'mx', 'my', 'object', 'opacity', 'order', 'origin', 'outline', 'overflow',
  'p', 'pb', 'pe', 'place', 'pl', 'pointer', 'position', 'pr', 'ps', 'pt', 'px', 'py', 'relative',
  'resize', 'right', 'ring', 'rotate', 'rounded', 'row', 'rows', 'scale', 'scroll', 'select',
  'self', 'shadow', 'shrink', 'size', 'skew', 'snap', 'space', 'sr', 'static', 'sticky', 'stroke',
  'subpixel', 'table', 'text', 'top', 'touch', 'tracking', 'transform', 'transition', 'translate',
  'truncate', 'underline', 'uppercase', 'vertical', 'visibility', 'w', 'whitespace', 'will',
  'z', 'zoom'
]);

/**
 * Props that should be excluded from CSS generation
 */
const EXCLUDED_PROPS = new Set([
  'data-class', 'data-role', 'className', 'component', 'children', 'key', 'ref'
]);

/**
 * Generate CSS content with @apply directives from component styles
 */
export function generateCSS(components: ComponentStyle[]): string {
  const cssRules: string[] = [];

  // Group components by selector to merge duplicate selectors
  const selectorMap = new Map<string, ComponentStyle[]>();

  for (const component of components) {
    const existing = selectorMap.get(component.selector) || [];
    existing.push(component);
    selectorMap.set(component.selector, existing);
  }

  // Generate CSS for each selector
  for (const [selector, componentStyles] of selectorMap) {
    const allProps = mergeProps(componentStyles);
    const cssClasses = convertPropsToClasses(allProps);

    if (cssClasses.length > 0) {
      cssRules.push(`.${selector} {\n  @apply ${cssClasses.join(' ')};\n}`);
    }
  }

  // Add header comment
  const header = `/*\n * Generated by UI8Kit CSS Preprocessor\n * Do not edit manually - this file is auto-generated\n * Generated on: ${new Date().toISOString()}\n */\n\n`;

  return header + cssRules.join('\n\n') + '\n';
}

/**
 * Merge props from multiple components with same selector
 */
function mergeProps(components: ComponentStyle[]): Record<string, any> {
  const merged: Record<string, any> = {};

  // Later components override earlier ones (for specificity)
  for (const component of components) {
    Object.assign(merged, component.props);
  }

  return merged;
}

/**
 * Convert utility props to CSS classes, filtering out non-utility props
 */
function convertPropsToClasses(props: Record<string, any>): string[] {
  const classes: string[] = [];

  for (const [key, value] of Object.entries(props)) {
    // Skip excluded props
    if (EXCLUDED_PROPS.has(key)) {
      continue;
    }

    // Skip non-utility props
    if (!UTILITY_PROPS.has(key)) {
      continue;
    }

    if (value === null || value === undefined || value === false) {
      continue;
    }

    if (value === true || value === '') {
      classes.push(key);
      continue;
    }

    const stringValue = String(value).trim();
    if (stringValue) {
      classes.push(`${key}-${stringValue}`);
    }
  }

  return classes;
}
