/**
 * Generated by @ui8kit/generator - variant elements
 * Do not edit manually - this file is auto-generated
 */

import { Badge } from "../components";

/**
 * Badge variant elements for documentation and reuse.
 * Each element has a single variant with corresponding data-class attribute.
 */
export function BadgeElements() {
  return (
    <>
  {/* Base */}
  <Badge data-class="badge">Badge</Badge>
  {/* Variants */}
  <Badge data-class="badge-destructive" variant="destructive">Badge Destructive</Badge>
  <Badge data-class="badge-info" variant="info">Badge Info</Badge>
  <Badge data-class="badge-lg" size="lg">Badge Lg</Badge>
  <Badge data-class="badge-outline" variant="outline">Badge Outline</Badge>
  <Badge data-class="badge-secondary" variant="secondary">Badge Secondary</Badge>
  <Badge data-class="badge-sm" size="sm">Badge Sm</Badge>
  <Badge data-class="badge-success" variant="success">Badge Success</Badge>
  <Badge data-class="badge-warning" variant="warning">Badge Warning</Badge>
  <Badge data-class="badge-xs" size="xs">Badge Xs</Badge>
    </>
  );
}

/**
 * Individual badge elements as named exports.
 * Use these for copy-paste or registry integration.
 */
export const BadgeBase = () => (
  <Badge data-class="badge">Badge</Badge>
);

export const BadgeDestructive = () => (
  <Badge data-class="badge-destructive" variant="destructive">Badge Destructive</Badge>
);

export const BadgeInfo = () => (
  <Badge data-class="badge-info" variant="info">Badge Info</Badge>
);

export const BadgeLg = () => (
  <Badge data-class="badge-lg" size="lg">Badge Lg</Badge>
);

export const BadgeOutline = () => (
  <Badge data-class="badge-outline" variant="outline">Badge Outline</Badge>
);

export const BadgeSecondary = () => (
  <Badge data-class="badge-secondary" variant="secondary">Badge Secondary</Badge>
);

export const BadgeSm = () => (
  <Badge data-class="badge-sm" size="sm">Badge Sm</Badge>
);

export const BadgeSuccess = () => (
  <Badge data-class="badge-success" variant="success">Badge Success</Badge>
);

export const BadgeWarning = () => (
  <Badge data-class="badge-warning" variant="warning">Badge Warning</Badge>
);

export const BadgeXs = () => (
  <Badge data-class="badge-xs" size="xs">Badge Xs</Badge>
);
