/**
 * Generated by @ui8kit/generator - variant elements
 * Do not edit manually - this file is auto-generated
 */

import { Button, ButtonContentAlign } from "../components";

/**
 * Button variant elements for documentation and reuse.
 * Each element has a single variant with corresponding data-class attribute.
 */
export function ButtonElements() {
  return (
    <>
  {/* Base */}
  <Button data-class="button">Button</Button>
  {/* Variants */}
  <Button data-class="button-content-align-between" contentAlign="between">ButtonContentAlign Between</Button>
  <Button data-class="button-content-align-center" contentAlign="center">ButtonContentAlign Center</Button>
  <Button data-class="button-content-align-end" contentAlign="end">ButtonContentAlign End</Button>
  <Button data-class="button-content-align-start" contentAlign="start">ButtonContentAlign Start</Button>
  <Button data-class="button-destructive" variant="destructive">Button Destructive</Button>
  <Button data-class="button-ghost" variant="ghost">Button Ghost</Button>
  <Button data-class="button-icon" size="icon">Button Icon</Button>
  <Button data-class="button-lg" size="lg">Button Lg</Button>
  <Button data-class="button-link" variant="link">Button Link</Button>
  <Button data-class="button-md" size="md">Button Md</Button>
  <Button data-class="button-outline" variant="outline">Button Outline</Button>
  <Button data-class="button-primary" variant="primary">Button Primary</Button>
  <Button data-class="button-secondary" variant="secondary">Button Secondary</Button>
  <Button data-class="button-sm" size="sm">Button Sm</Button>
  <Button data-class="button-xl" size="xl">Button Xl</Button>
  <Button data-class="button-xs" size="xs">Button Xs</Button>
  {/* Sub-components */}
  <ButtonContentAlign data-class="button-content-align">Button ContentAlign</ButtonContentAlign>
    </>
  );
}

/**
 * Individual button elements as named exports.
 * Use these for copy-paste or registry integration.
 */
export const ButtonBase = () => (
  <Button data-class="button">Button</Button>
);

export const ButtonBetween = () => (
  <Button data-class="button-content-align-between" contentAlign="between">ButtonContentAlign Between</Button>
);

export const ButtonCenter = () => (
  <Button data-class="button-content-align-center" contentAlign="center">ButtonContentAlign Center</Button>
);

export const ButtonEnd = () => (
  <Button data-class="button-content-align-end" contentAlign="end">ButtonContentAlign End</Button>
);

export const ButtonStart = () => (
  <Button data-class="button-content-align-start" contentAlign="start">ButtonContentAlign Start</Button>
);

export const ButtonDestructive = () => (
  <Button data-class="button-destructive" variant="destructive">Button Destructive</Button>
);

export const ButtonGhost = () => (
  <Button data-class="button-ghost" variant="ghost">Button Ghost</Button>
);

export const ButtonIcon = () => (
  <Button data-class="button-icon" size="icon">Button Icon</Button>
);

export const ButtonLg = () => (
  <Button data-class="button-lg" size="lg">Button Lg</Button>
);

export const ButtonLink = () => (
  <Button data-class="button-link" variant="link">Button Link</Button>
);

export const ButtonMd = () => (
  <Button data-class="button-md" size="md">Button Md</Button>
);

export const ButtonOutline = () => (
  <Button data-class="button-outline" variant="outline">Button Outline</Button>
);

export const ButtonPrimary = () => (
  <Button data-class="button-primary" variant="primary">Button Primary</Button>
);

export const ButtonSecondary = () => (
  <Button data-class="button-secondary" variant="secondary">Button Secondary</Button>
);

export const ButtonSm = () => (
  <Button data-class="button-sm" size="sm">Button Sm</Button>
);

export const ButtonXl = () => (
  <Button data-class="button-xl" size="xl">Button Xl</Button>
);

export const ButtonXs = () => (
  <Button data-class="button-xs" size="xs">Button Xs</Button>
);

export const ButtonContentAlignElement = () => (
  <ButtonContentAlign data-class="button-content-align">Button ContentAlign</ButtonContentAlign>
);
