/**
 * Generated by @ui8kit/generator - variant elements
 * Do not edit manually - this file is auto-generated
 */

import type { ReactNode, ComponentProps } from "react";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "../components";
import type { CardProps, CardContentProps, CardDescriptionProps, CardFooterProps, CardHeaderProps, CardTitleProps } from "../components";

/**
 * Card variant elements for documentation and reuse.
 * Each element has a single variant with corresponding data-class attribute.
 */
export function CardElements() {
  return (
    <>
  {/* Base */}
  <Card data-class="card">Card</Card>
  {/* Variants */}
  <Card data-class="card-filled" variant="filled">Card Filled</Card>
  <Card data-class="card-outlined" variant="outlined">Card Outlined</Card>
  {/* Sub-components */}
  <CardContent data-class="card-content">Card Content</CardContent>
  <CardDescription data-class="card-description">Card Description</CardDescription>
  <CardFooter data-class="card-footer">Card Footer</CardFooter>
  <CardHeader data-class="card-header">Card Header</CardHeader>
  <CardTitle data-class="card-title">Card Title</CardTitle>
    </>
  );
}

/**
 * Reusable card element components.
 * Accept children and props for composition.
 */
/** Base Card with semantic data-class */
export const CardElement = ({ children, ...props }: Omit<ComponentProps<typeof Card>, "data-class"> & { children?: ReactNode }) => (
  <Card data-class="card" {...props}>{children ?? "Card"}</Card>
);

/** Card with filled variant */
export const CardFilled = ({ children, ...props }: Omit<ComponentProps<typeof Card>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Card data-class="card-filled" variant="filled" {...props}>{children ?? "Card Filled"}</Card>
);

/** Card with outlined variant */
export const CardOutlined = ({ children, ...props }: Omit<ComponentProps<typeof Card>, "data-class" | "variant"> & { children?: ReactNode }) => (
  <Card data-class="card-outlined" variant="outlined" {...props}>{children ?? "Card Outlined"}</Card>
);

/** Card Content with semantic data-class */
export const CardContentElement = ({ children, ...props }: Omit<ComponentProps<typeof CardContent>, "data-class"> & { children?: ReactNode }) => (
  <CardContent data-class="card-content" {...props}>{children ?? "Card Content"}</CardContent>
);

/** Card Description with semantic data-class */
export const CardDescriptionElement = ({ children, ...props }: Omit<ComponentProps<typeof CardDescription>, "data-class"> & { children?: ReactNode }) => (
  <CardDescription data-class="card-description" {...props}>{children ?? "Card Description"}</CardDescription>
);

/** Card Footer with semantic data-class */
export const CardFooterElement = ({ children, ...props }: Omit<ComponentProps<typeof CardFooter>, "data-class"> & { children?: ReactNode }) => (
  <CardFooter data-class="card-footer" {...props}>{children ?? "Card Footer"}</CardFooter>
);

/** Card Header with semantic data-class */
export const CardHeaderElement = ({ children, ...props }: Omit<ComponentProps<typeof CardHeader>, "data-class"> & { children?: ReactNode }) => (
  <CardHeader data-class="card-header" {...props}>{children ?? "Card Header"}</CardHeader>
);

/** Card Title with semantic data-class */
export const CardTitleElement = ({ children, ...props }: Omit<ComponentProps<typeof CardTitle>, "data-class"> & { children?: ReactNode }) => (
  <CardTitle data-class="card-title" {...props}>{children ?? "Card Title"}</CardTitle>
);
