/**
 * Generated by @ui8kit/generator - variant elements
 * Do not edit manually - this file is auto-generated
 */

import { Card } from "../components";

/**
 * Card variant elements for documentation and reuse.
 * Each element has a single variant with corresponding data-class attribute.
 */
export function CardElements() {
  return (
    <>
  {/* Base */}
  <Card data-class="card">Card</Card>
  <Card data-class="card-filled" variant="filled">Card Filled</Card>
  <Card data-class="card-outlined" variant="outlined">Card Outlined</Card>
    </>
  );
}

/**
 * Individual card elements as named exports.
 * Use these for copy-paste or registry integration.
 */
export const CardBase = () => (
  <Card data-class="card">Card</Card>
);

export const CardFilled = () => (
  <Card data-class="card-filled" variant="filled">Card Filled</Card>
);

export const CardOutlined = () => (
  <Card data-class="card-outlined" variant="outlined">Card Outlined</Card>
);
