/**
 * Generated by @ui8kit/generator - variant elements
 * Do not edit manually - this file is auto-generated
 */

import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "../components";

/**
 * Card variant elements for documentation and reuse.
 * Each element has a single variant with corresponding data-class attribute.
 */
export function CardElements() {
  return (
    <>
  {/* Base */}
  <Card data-class="card">Card</Card>
  {/* Variants */}
  <Card data-class="card-filled" variant="filled">Card Filled</Card>
  <Card data-class="card-outlined" variant="outlined">Card Outlined</Card>
  {/* Sub-components */}
  <CardContent data-class="card-content">Card Content</CardContent>
  <CardDescription data-class="card-description">Card Description</CardDescription>
  <CardFooter data-class="card-footer">Card Footer</CardFooter>
  <CardHeader data-class="card-header">Card Header</CardHeader>
  <CardTitle data-class="card-title">Card Title</CardTitle>
    </>
  );
}

/**
 * Individual card elements as named exports.
 * Use these for copy-paste or registry integration.
 */
export const CardBase = () => (
  <Card data-class="card">Card</Card>
);

export const CardFilled = () => (
  <Card data-class="card-filled" variant="filled">Card Filled</Card>
);

export const CardOutlined = () => (
  <Card data-class="card-outlined" variant="outlined">Card Outlined</Card>
);

export const CardContentElement = () => (
  <CardContent data-class="card-content">Card Content</CardContent>
);

export const CardDescriptionElement = () => (
  <CardDescription data-class="card-description">Card Description</CardDescription>
);

export const CardFooterElement = () => (
  <CardFooter data-class="card-footer">Card Footer</CardFooter>
);

export const CardHeaderElement = () => (
  <CardHeader data-class="card-header">Card Header</CardHeader>
);

export const CardTitleElement = () => (
  <CardTitle data-class="card-title">Card Title</CardTitle>
);
