/**
 * Generated by @ui8kit/generator - variant elements
 * Do not edit manually - this file is auto-generated
 */

import { Grid } from "../components";

/**
 * Grid variant elements for documentation and reuse.
 * Each element has a single variant with corresponding data-class attribute.
 */
export function GridElements() {
  return (
    <>
  {/* Base */}
  <Grid data-class="grid">Grid</Grid>
  {/* Variants */}
  <Grid data-class="grid-1-2" cols="1-2">Grid 12</Grid>
  <Grid data-class="grid-1-2-3" cols="1-2-3">Grid 123</Grid>
  <Grid data-class="grid-1-2-3-4" cols="1-2-3-4">Grid 1234</Grid>
  <Grid data-class="grid-1-2-4" cols="1-2-4">Grid 124</Grid>
  <Grid data-class="grid-1-2-6" cols="1-2-6">Grid 126</Grid>
  <Grid data-class="grid-1-3" cols="1-3">Grid 13</Grid>
  <Grid data-class="grid-1-3-4" cols="1-3-4">Grid 134</Grid>
  <Grid data-class="grid-1-3-6" cols="1-3-6">Grid 136</Grid>
  <Grid data-class="grid-1-4" cols="1-4">Grid 14</Grid>
  <Grid data-class="grid-1-5" cols="1-5">Grid 15</Grid>
  <Grid data-class="grid-1-6" cols="1-6">Grid 16</Grid>
  <Grid data-class="grid-2-3" cols="2-3">Grid 23</Grid>
  <Grid data-class="grid-2-3-4" cols="2-3-4">Grid 234</Grid>
  <Grid data-class="grid-2-4" cols="2-4">Grid 24</Grid>
  <Grid data-class="grid-2-5" cols="2-5">Grid 25</Grid>
  <Grid data-class="grid-2-6" cols="2-6">Grid 26</Grid>
  <Grid data-class="grid-3-4" cols="3-4">Grid 34</Grid>
  <Grid data-class="grid-3-5" cols="3-5">Grid 35</Grid>
  <Grid data-class="grid-3-6" cols="3-6">Grid 36</Grid>
  <Grid data-class="grid-4-5" cols="4-5">Grid 45</Grid>
  <Grid data-class="grid-4-6" cols="4-6">Grid 46</Grid>
  <Grid data-class="grid-5-6" cols="5-6">Grid 56</Grid>
    </>
  );
}

/**
 * Individual grid elements as named exports.
 * Use these for copy-paste or registry integration.
 */
export const GridBase = () => (
  <Grid data-class="grid">Grid</Grid>
);

export const Grid12 = () => (
  <Grid data-class="grid-1-2" cols="1-2">Grid 12</Grid>
);

export const Grid123 = () => (
  <Grid data-class="grid-1-2-3" cols="1-2-3">Grid 123</Grid>
);

export const Grid1234 = () => (
  <Grid data-class="grid-1-2-3-4" cols="1-2-3-4">Grid 1234</Grid>
);

export const Grid124 = () => (
  <Grid data-class="grid-1-2-4" cols="1-2-4">Grid 124</Grid>
);

export const Grid126 = () => (
  <Grid data-class="grid-1-2-6" cols="1-2-6">Grid 126</Grid>
);

export const Grid13 = () => (
  <Grid data-class="grid-1-3" cols="1-3">Grid 13</Grid>
);

export const Grid134 = () => (
  <Grid data-class="grid-1-3-4" cols="1-3-4">Grid 134</Grid>
);

export const Grid136 = () => (
  <Grid data-class="grid-1-3-6" cols="1-3-6">Grid 136</Grid>
);

export const Grid14 = () => (
  <Grid data-class="grid-1-4" cols="1-4">Grid 14</Grid>
);

export const Grid15 = () => (
  <Grid data-class="grid-1-5" cols="1-5">Grid 15</Grid>
);

export const Grid16 = () => (
  <Grid data-class="grid-1-6" cols="1-6">Grid 16</Grid>
);

export const Grid23 = () => (
  <Grid data-class="grid-2-3" cols="2-3">Grid 23</Grid>
);

export const Grid234 = () => (
  <Grid data-class="grid-2-3-4" cols="2-3-4">Grid 234</Grid>
);

export const Grid24 = () => (
  <Grid data-class="grid-2-4" cols="2-4">Grid 24</Grid>
);

export const Grid25 = () => (
  <Grid data-class="grid-2-5" cols="2-5">Grid 25</Grid>
);

export const Grid26 = () => (
  <Grid data-class="grid-2-6" cols="2-6">Grid 26</Grid>
);

export const Grid34 = () => (
  <Grid data-class="grid-3-4" cols="3-4">Grid 34</Grid>
);

export const Grid35 = () => (
  <Grid data-class="grid-3-5" cols="3-5">Grid 35</Grid>
);

export const Grid36 = () => (
  <Grid data-class="grid-3-6" cols="3-6">Grid 36</Grid>
);

export const Grid45 = () => (
  <Grid data-class="grid-4-5" cols="4-5">Grid 45</Grid>
);

export const Grid46 = () => (
  <Grid data-class="grid-4-6" cols="4-6">Grid 46</Grid>
);

export const Grid56 = () => (
  <Grid data-class="grid-5-6" cols="5-6">Grid 56</Grid>
);
