/**
 * Generated by @ui8kit/generator - variant elements
 * Do not edit manually - this file is auto-generated
 */

import { Image, ImageFit, ImagePosition } from "../components";

/**
 * Image variant elements for documentation and reuse.
 * Each element has a single variant with corresponding data-class attribute.
 */
export function ImageElements() {
  return (
    <>
  {/* Base */}
  <Image data-class="image">Image</Image>
  {/* Variants */}
  <Image data-class="aspect-ratio-square" aspect="square">AspectRatio Square</Image>
  <Image data-class="aspect-ratio-video" aspect="video">AspectRatio Video</Image>
  <Image data-class="image-fit-contain" fit="contain">ImageFit Contain</Image>
  <Image data-class="image-fit-fill" fit="fill">ImageFit Fill</Image>
  <Image data-class="image-fit-none" fit="none">ImageFit None</Image>
  <Image data-class="image-fit-scale-down" fit="scale-down">ImageFit ScaleDown</Image>
  <Image data-class="image-position-bottom" position="bottom">ImagePosition Bottom</Image>
  <Image data-class="image-position-bottom-left" position="bottom-left">ImagePosition BottomLeft</Image>
  <Image data-class="image-position-bottom-right" position="bottom-right">ImagePosition BottomRight</Image>
  <Image data-class="image-position-left" position="left">ImagePosition Left</Image>
  <Image data-class="image-position-right" position="right">ImagePosition Right</Image>
  <Image data-class="image-position-top" position="top">ImagePosition Top</Image>
  <Image data-class="image-position-top-left" position="top-left">ImagePosition TopLeft</Image>
  <Image data-class="image-position-top-right" position="top-right">ImagePosition TopRight</Image>
  <Image data-class="image-with-placeholder" withPlaceholder="with-placeholder">Image WithPlaceholder</Image>
  {/* Sub-components */}
  <ImageFit data-class="image-fit">Image Fit</ImageFit>
  <ImagePosition data-class="image-position">Image Position</ImagePosition>
    </>
  );
}

/**
 * Individual image elements as named exports.
 * Use these for copy-paste or registry integration.
 */
export const ImageBase = () => (
  <Image data-class="image">Image</Image>
);

export const ImageSquare = () => (
  <Image data-class="aspect-ratio-square" aspect="square">AspectRatio Square</Image>
);

export const ImageVideo = () => (
  <Image data-class="aspect-ratio-video" aspect="video">AspectRatio Video</Image>
);

export const ImageContain = () => (
  <Image data-class="image-fit-contain" fit="contain">ImageFit Contain</Image>
);

export const ImageFill = () => (
  <Image data-class="image-fit-fill" fit="fill">ImageFit Fill</Image>
);

export const ImageNone = () => (
  <Image data-class="image-fit-none" fit="none">ImageFit None</Image>
);

export const ImageScaleDown = () => (
  <Image data-class="image-fit-scale-down" fit="scale-down">ImageFit ScaleDown</Image>
);

export const ImageBottom = () => (
  <Image data-class="image-position-bottom" position="bottom">ImagePosition Bottom</Image>
);

export const ImageBottomLeft = () => (
  <Image data-class="image-position-bottom-left" position="bottom-left">ImagePosition BottomLeft</Image>
);

export const ImageBottomRight = () => (
  <Image data-class="image-position-bottom-right" position="bottom-right">ImagePosition BottomRight</Image>
);

export const ImageLeft = () => (
  <Image data-class="image-position-left" position="left">ImagePosition Left</Image>
);

export const ImageRight = () => (
  <Image data-class="image-position-right" position="right">ImagePosition Right</Image>
);

export const ImageTop = () => (
  <Image data-class="image-position-top" position="top">ImagePosition Top</Image>
);

export const ImageTopLeft = () => (
  <Image data-class="image-position-top-left" position="top-left">ImagePosition TopLeft</Image>
);

export const ImageTopRight = () => (
  <Image data-class="image-position-top-right" position="top-right">ImagePosition TopRight</Image>
);

export const ImageWithPlaceholder = () => (
  <Image data-class="image-with-placeholder" withPlaceholder="with-placeholder">Image WithPlaceholder</Image>
);

export const ImageFitElement = () => (
  <ImageFit data-class="image-fit">Image Fit</ImageFit>
);

export const ImagePositionElement = () => (
  <ImagePosition data-class="image-position">Image Position</ImagePosition>
);
